USE BLOG 
GO

CREATE TABLE BLOGS 
(
	ID INT IDENTITY(1,1) NOT NULL,
	TITLE NVARCHAR(MAX) NOT NULL,
	DESCRIPTION_SHORT NVARCHAR(MAX),
	DETAIL NVARCHAR(MAX), 
	IMAGE IMAGE,
	CATEGORY INT NOT NULL,
	LOCATIONS NVARCHAR(MAX) NOT NULL,
	PUBLICS BIT NOT NULL,
	DATE_PUBLIC DATE NOT NULL
)
GO
